ALTER TABLE "match"
    ADD COLUMN IF NOT EXISTS venue VARCHAR(100) NOT NULL DEFAULT 'Unknown';

CREATE TABLE IF NOT EXISTS match_goal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fk_match_id BIGINT NOT NULL,
    fk_team_id BIGINT NOT NULL,
    goal_minute SMALLINT NOT NULL CHECK (goal_minute BETWEEN 1 AND 120),
    stoppage_minute SMALLINT CHECK (stoppage_minute BETWEEN 0 AND 30),
    CONSTRAINT fk_match_goal_match
        FOREIGN KEY (fk_match_id) REFERENCES "match"(id) ON DELETE CASCADE,
    CONSTRAINT fk_match_goal_team
        FOREIGN KEY (fk_team_id) REFERENCES team(id)
);

CREATE INDEX IF NOT EXISTS idx_match_goal_match_id ON match_goal(fk_match_id);
