spring.application.name=Football_Manager
spring.datasource.url=jdbc:postgresql://db.lxmqwgkgyuhjkcqgcdzk.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=mukn4nrpsuboO68R
spring.jpa.hibernate.ddl-auto=update